// pages/index.tsx

import Head from "next/head";
import { Inter } from "next/font/google";
import { useDataByContext } from "@/ContextProvider";
import { useState } from "react";
import Form from "@/components/Form";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { guineaList } = useDataByContext(); //custom hook per estrarre i value passati tramite il provider del context
  const [formData, setFormData] = useState({
    nome: "",
    cognome: "",
    email: "",
    cellulare: "",
    opzione: "",
  });

  const handleChange = (e: any) => {
    const { name, value } = e.target;
    console.log(name);
    console.log(value);
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  const handleSubmit = (e: any) => {
    e.preventDefault();
    console.log(formData);
  };

  return (
    <>
      <Head>
        <title>Guinea Pigs Adoption</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto py-8">
        <div className="mb-8">
          <h3 className="text-2xl font-bold mb-4">Lista Guinea pigs</h3>
        </div>
      </div>
    </>
  );
}
