// pages/index.tsx

import Head from "next/head";
import { Inter } from "next/font/google";
import { useDataByContext } from "@/ContextProvider";
import { useState } from "react";
import Form from "@/components/Form";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { guineaList } = useDataByContext(); //custom hook per estrarre i value passati tramite il provider del context
  //const { getGuineaPigList } = useDataByContext();

  const [formData, setFormData] = useState({
    nome: "",
    cognome: "",
    email: "",
    cellulare: "",
    opzione: "",
  });

  console.log("HOME", guineaList);

  const handleChange = (e: any) => {
    const { name, value } = e.target;
    console.log(name);
    console.log(value);
    setFormData((prevData) => ({
      ...prevData,
      [name]: value,
    }));
  };

  const handleSubmit = (e: any) => {
    e.preventDefault();
    console.log(formData);
  };

  return (
    <>
      <Head>
        <title>Guinea Pigs Adoption</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container mx-auto py-8">
        <div className="img">
          <img
            src="https://www.nonsprecare.it/wp-content/uploads/2021/10/porcellino-dindia.jpg"
            alt=" un porcellino d india che viene abbracciato e cocolato dolcemente da un bambino"
            width="1500"
          ></img>
        </div>
        <div className="mb-8">
          <h3 className="text-2xl font-bold mb-4">
            Carattere delle cavie e altre informazioni
          </h3>
          <p className="text-lg mb-4">
            e cavie sono roditori istricomorfi originari del Sud America. Hanno
            corpo compatto e arrotondato, zampe corte e delicate e sono
            sprovviste di coda. I maschi sono più grandi delle femmine e pesano,
            da adulti, tra i 900 e i 1200 grammi (contro i 700-900 delle
            femmine). Vivono approssimativamente 5-8 anni, a volte anche più a
            lungo. Sono animali crepuscolari, sono cioè maggiormente attive
            nelle prime ore del giorno e alla sera. Durante le ore pomeridiane e
            la notte dormono per la maggior parte del tempo. Sono animali
            sociali e in libertà vivono in piccoli gruppi di circa una decina di
            individui, composti da molte femmine con un maschio dominante. Non
            amano la solitudine, e apprendono dai loro simili soprattutto per
            imitazione. Raramente scavano tane ma utilizzano come rifugio buchi
            e anfratti del terreno o le tane abbandonate di altri animali. Non
            si arrampicano e non riescono a saltare ostacoli, la loro migliore
            arma di difesa è la fuga, infatti sono in grado di correre molto
            velocemente, anche in tenera età. Sono in generale molto timide e
            paurose, hanno la tendenza a rifuggire dai rumori forti o
            sconosciuti e si muovono preferibilmente in gruppo, di solito in
            fila indiana. Mordono molto raramente e anche se vengono spaventate
            o attaccate di norma preferiscono fuggire o immobilizzarsi piuttosto
            che fronteggiare l’aggressore. La loro alimentazione è completamente
            vegetariana e comprende allo stato selvatico un gran numero di erbe
            e arbusti. Quando la cavia non dorme, passa il tempo andando in
            cerca di cibo e mangiando, muovendosi molto. Le cavie posseggono un
            complesso sistema di comunicazione che comprende diversi suoni che
            possono assumere sfumature e significati diversi a seconda della
            situazione. Il suono più tipico è il forte fischio che viene
            prodotto per richiedere cibo o attenzioni o in caso di pericolo.
          </p>
          <h3 className="text-2xl font-bold mb-4">Consigli veterinari</h3>

          <p className="text-lg">
            Alla luce di tutto questo sconsigliamo vivamente di tenere una cavia
            da sola o chiusa in gabbia. Le cavie hanno un estremo bisogno della
            compagnia dei loro simili, e di potersi muovere. La condizione
            migliore si raggiunge tenendo un piccolo gruppo (3-5) di cavie,
            preferibilmente composto da un maschio (sterilizzato) e più femmine.
            Poiché questo non è ovviamente sempre possibile, un buon compromesso
            è la coppia, che può essere costituita da due soggetti dello stesso
            sesso o di sesso opposto (maschio sterilizzato). La sterilizzazione
            del maschio è un intervento semplice e veloce, che comporta un
            rischio molto contenuto rispetto alla sterilizzazione della femmina,
            caratterizzata da un’invasività decisamente maggiore. Dal momento
            che le cavie sono animali paurosi vanno trattati con calma e
            delicatezza, evitando movimenti improvvisi e rumori forti. A
            dispetto di quanto si crede comunemente non sono animali adatti ai
            bambini a causa della loro conformazione fisica delicata e poco
            resistente a urti e cadute. Una caduta da soli 20 cm potrebbe
            causare fratture alle zampe o lesioni interne pericolosissime.
          </p>
        </div>
      </div>

      {/* GESTIONE DINAMICA DELLE CARD */}
      <div className="card_of_a_pig">
        <div className="max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
          <a href="#">
            <img
              className="https://www.zooeasy.com/wp-content/uploads/2019/07/jack-catalano-q1pw1dOW0_0-unsplash.jpg"
              src="/docs/images/blog/image-1.jpg"
              alt=""
            />
          </a>
          <div className="p-5">
            <a href="#">
              <h5>Noteworthy technology acquisitions 2021</h5>
            </a>
          </div>
        </div>
      </div>
    </>
  );
}
