import Head from "next/head";
import { Inter } from "next/font/google";
import { useDataByContext } from "@/ContextProvider";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { guineaList } = useDataByContext(); //custom hook per estrarre i value passati tramite il provider del context
  return (
    <>
      <Head>
        <title>Guinea Pigs Adoption</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <ul>
          {guineaList?.map((elem) => (
            <li>{elem.name}</li>
          ))}
        </ul>
      </div>
    </>
  );
}
